/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

export interface Users {
  email: string;
  id: string;
  login: string;
  password: string;
}

export interface DB {
  users: Users;
}
